# docker-compose

mysql8:
  container_name: yoshi-mysql8
  build: mysql8
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  ports:
    - "3306:3306"

yesod_api_server:
  container_name: yoshi-yesod_api_server
  build: yesod_api_server
  ports:
    - "4444:4444"

